services:
    wiki:
        container_name: wiki
        image: requarks/wiki
        init: true
        environment:
            DB_TYPE: sqlite
            DB_FILEPATH: /var/wiki/wiki.db
        restart: unless-stopped
        volumes:
        - /home/wiki/data:/var/wiki
        ports:
            - 44322:3000
