services:
    wiki:
        container_name: wiki
        image: requarks/wiki
        init: true
        restart: unless-stopped
        volumes:
        - /home/wiki/data:/var/wiki
        - /home/wiki/config.yml:/wiki/config.yml
        ports:
            - 44322:3000
