server {
    listen 443 ssl;
    server_name wiki.vanane.net;
    ssl_certificate     /var/certs/fullchain.pem;
    ssl_certificate_key /var/certs/privkey.pem;

    location / {
        proxy_pass http://localhost:44322;
    }
}
